controller_list:
  - name: fake_mrdummy_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_joint1
      - arm1_joint
      - arm2_joint
      - wirst1_joint
      - wirst2_joint
initial:  # Define initial robot poses per group
  - group: mrdummy
    pose: home