mrdummy_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - shoulder_joint1
    - arm1_joint
    - arm2_joint
    - wirst1_joint
    - wirst2_joint
  gains:
    shoulder_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wirst1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wirst2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1